development:
  adapter: postgresql
  encoding: unicode
  database: ror_test_development
  pool: 5
  username: postgres
  password: gurus

test:
   adapter: postgresql
   encoding: unicode
   database: ror_test_test
   pool: 5
   username: postgres
   password: gurus